
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:87 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1271 (message)"
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:87 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      riscv32-elf-gcc.gnu (2023-06-30_nds32le-elf-mculib-v5f-8376cb5a7ad) 10.3.0
      Copyright (C) 2020 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:87 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/TelinkIoTStudio/RDS/V5.1.2/toolchains/nds32le-elf-mculib-v5f/bin/riscv32-elf-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        C:/Users/ansel/Desktop/telink_b91m_btble_dual_mode_general_sdk-master/sdk/cmake_builds/telink_b91_btble_sdk/Telink_TLSR9_D25F_GCC_10/CMakeFiles/4.0.2/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ansel/.Telink_Tools/cmake-4.0.2-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:87 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/TelinkIoTStudio/RDS/V5.1.2/toolchains/nds32le-elf-mculib-v5f/bin/riscv32-elf-g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/ansel/Desktop/telink_b91m_btble_dual_mode_general_sdk-master/sdk/cmake_builds/telink_b91_btble_sdk/Telink_TLSR9_D25F_GCC_10/CMakeFiles/4.0.2/CompilerIdCXX/a.out
      
...
